

```{r}

library(datasets)
?datasets

```


```{r}
library(help = "datasets")
```



```{r}

head(datasets::ToothGrowth)
?ToothGrowth
```

```{r}
head(datasets::UKgas)
?UKgas
```


```{r}

head(datasets::PlantGrowth)
?PlantGrowth
```

```{r}
head(datasets::quakes)
?quakes
```

```{r}
head(datasets::trees)
?trees
```


```{r}

library(ggplot2)

plot1 <- ggplot(trees, aes(Girth,Volume)) + geom_point(colour = "blue", size = 2)
plot1 
cor.test(trees$Girth, trees$Volume)
plot2_bp <- ggplot(trees,aes(Girth,Volume,group = 1)) + geom_boxplot()
plot2_bp
```

```{r}
head(datasets::cars)
?cars
```
```{r}
plot2 <- ggplot(cars, aes(speed,dist)) + geom_point(colour = "blue", size = 2)
plot2 
cor.test(cars$speed, cars$dist)
```


```{r}
plot2_bp <- ggplot(cars,aes(speed,dist,group = 1)) + geom_boxplot()
plot2_bp
```



```{r}
head(datasets::state.x77)
?state.x77
as.data.frame(state.x77)
```


```{r}
# Setting the randomizer's seed
set.seed(123)

#Split your data into training and test sets
trees_sample <- sample(c(TRUE, FALSE), nrow(trees), replace = T, prob = c(0.6,0.4))
trees_train <- trees[sample, ]
trees_test <- trees[!sample, ]


```



```{r}

trees_model <- lm(Volume ~ Girth, data = trees_train)

```
```{r}
cars_sample <- sample(c(TRUE, FALSE), nrow(cars), replace = T, prob = c(0.6,0.4))
cars_train <- cars[sample, ]
cars_test <- cars[!sample, ]
```

```{r}
cars_model <- lm(dist ~ speed, data = cars_train)
```



```{r}
# Find the RSE of each model
sigma(trees_model)
sigma(cars_model)

```


```{r}
# Find the R Squared value of each model
summary(trees_model)$r.squared
summary(cars_model)$r.squared
```



```{r}
# Print the summary of each model
summary(trees_model)
summary(cars_model)
```




```{r}
#save predicted and residual values to df
trees_train$estimate <- predict(trees_model)
trees_train$residuals <- residuals(trees_model)

cars_train$estimate <- predict(cars_model)
cars_train$residuals <- residuals(cars_model)

#create visualization

ggplot(trees_train, aes(Girth, Volume)) +
geom_point(colour = "red") + 
geom_point(aes(y = estimate), colour = "blue") +
geom_segment(aes(xend = Girth, yend = estimate), colour = "black")

ggplot(cars_train, aes(speed, dist)) +
geom_point(colour = "red") + 
geom_point(aes(y = estimate), colour = "blue") +
geom_segment(aes(xend = speed, yend = estimate), colour = "black")


```



```{r}
# Add a LOESS smoother to your scatterplot
plot1 <- ggplot(trees_train, aes(Girth,Volume)) + geom_point(colour = "blue", size = 2) + geom_smooth(method = "lm") + geom_smooth(se = FALSE, color = "red")
plot1 

plot2 <- ggplot(cars_train, aes(speed,dist)) + geom_point(colour = "blue", size = 2) + geom_smooth(method = "lm") + geom_smooth(se = FALSE, color = "red")
plot2 
```





```{r}
# Create a multiple linear regression model
trees_model_multivar <- lm(Volume ~ Girth + Height, data = trees_train)
summary(trees_model_multivar)
```




